<?php

namespace AppBundle\Repository;

/**
 * jeuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jeuxRepository extends \Doctrine\ORM\EntityRepository
{
}
