<?php

namespace AppBundle\Repository;

/**
 * telephoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class telephoneRepository extends \Doctrine\ORM\EntityRepository
{
}
