<?php

namespace AppBundle\Repository;

/**
 * villesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class villesRepository extends \Doctrine\ORM\EntityRepository
{
}
